version: '3.1'
services:
  wordpress:
    image: rojen/php5.6-docker:no-mysqli
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./public_html:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
volumes:
  db:
